const DEFAULT_MAX_PAGES = 20
const DEFAULT_MAX_DEPTH = 2
const CRAWL_CACHE_HOURS = 24
const DAILY_CRAWL_LIMIT = Number(process.env.DAILY_CRAWL_LIMIT || 5)
const GLOBAL_CRAWL_CONCURRENCY = Number(process.env.GLOBAL_CRAWL_CONCURRENCY || 3)

module.exports = {
  DEFAULT_MAX_PAGES,
  DEFAULT_MAX_DEPTH,
  CRAWL_CACHE_HOURS,
  DAILY_CRAWL_LIMIT,
  GLOBAL_CRAWL_CONCURRENCY,
}
